### ISSUE TITLE
Can you explain how In details how to use it ? like workFlow1  and workFlow2 as examples

### ISSUE THREAD

**Issue by SaitejaGurram** [tonyhallett/workflow-run-conclusion-dispatch-action#45]
Can you explain by taking 2 workflows, on success of the workflow1 then only workflow2 is triggered or even though triggered with failed state

**Comment by tonyhallett** [comment]
Here is the code https://github.com/tonyhallett/github-actions/blob/master/src/workflow/workflowRunConclusionDispatchAction.ts

You create a workflow run workflow for a workflow that you want to react to based upon its conclusion.  This action then dispatches an event that includes the name of the workflow you are interested in and the conclusion.
You can then handle the conclusion you are interested in.

**Comment by tonyhallett** [comment]
So instead of
Workflow -> Handle and check conclusion
Workflow -> Repository dispatch
  -> Handle success
  -> Handle failure
  -> Handle cancelled
  ...

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run

You can only filter by activity types - completed / requested.

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run

> Many workflow_run keys, such as head_branch, conclusion, and pull_requests are the same as those in a check_suite object.

> Can be one of success, failure, neutral, cancelled, timed_out, action_required or stale.
